apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-dep
spec:
 replicas: 3
 template:
   metadata:
     name: dummy-po
     labels:
       type: dummy
   spec:
     containers:
       - name: dummy-cont
         image: nginx
 selector:
   matchLabels:
     type: dummy
